### ISSUE TITLE
Error After installing

### ISSUE THREAD

**Issue by tech-ninja007** [hieulw/cicflowmeter#2]
I installed it on Ubuntu VM. (pip install cicflowmeter)

$cicflowmeter -i ens33 -c test.csv
Error:
Exception in thread AsyncSniffer:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scapy/sendrecv.py", line 1254, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.10/dist-packages/cicflowmeter/flow_session.py", line 99, in on_packet_received
    flow.add_packet(packet, direction)
  File "/usr/local/lib/python3.10/dist-packages/cicflowmeter/flow.py", line 212, in add_packet
    self.update_subflow(packet)
  File "/usr/local/lib/python3.10/dist-packages/cicflowmeter/flow.py", line 245, in update_subflow
    if (packet.time - (last_timestamp / Decimal("1e6"))) > constants.CLUMP_TIMEOUT:
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'

**Comment by hieulw** [comment]
could you provide the python version ?

**Comment by hieulw** [comment]
@tech-ninja007  I just updated new version, please update cicflowmeter and let me know if the issue is still persist.

**Comment by tech-ninja007** [comment]
> @tech-ninja007 I just updated new version, please update cicflowmeter and let me know if the issue is still persist.

I am still enable to resolve the issue. I am not that good with Python. I wanted to use the tool in my project.

**Comment by przemo71J** [comment]
With this "https://www.youtube.com/watch?v=iM2fBy8FUnw&t=531s" you will be able to fix this problem, but still in cicflowmeter there are few issues I noticed (live capturing for example) but can be fixed after debugging

**Comment by tech-ninja007** [comment]
@przemo71J Thanks for sharing the video.
I apologize. I keep encountering this error.

sudo cicflowmeter -f test.pcap -c test.csv
Exception in thread AsyncSniffer:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 1116, in _run
    sniff_sockets.update((PcapReader(
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 1118, in <genexpr>
    tcpdump(fname,
  File "/usr/lib/python3/dist-packages/scapy/utils.py", line 2715, in tcpdump
    with PcapReader(pktlist) as rd:
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/scapy/utils.py", line 1199, in __call__
    raise Scapy_Exception("Not a supported capture file")
scapy.error.Scapy_Exception: Not a supported capture file

sudo cicflowmeter -i ens33 -c test.csv
Traceback (most recent call last):
  File "/usr/local/bin/cicflowmeter", line 33, in <module>
    sys.exit(load_entry_point('cicflowmeter==0.1.9', 'console_scripts', 'cicflowmeter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/cicflowmeter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 967, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 564, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for cicflowmeter
