### ISSUE TITLE
Issue in convert pcap file to flow csv

### ISSUE THREAD

**Issue by emanmaali** [hieulw/cicflowmeter#3]
Hi CICFlowMeter Team, 

Can you please help in the following? 

![Uploading CICFlowMeterError.png…]()

Thanks

**Comment by emanmaali** [comment]
here is the error in details, 

eading from file minitestbed_new_pcaps_202212-google_home_mini.pcap, link-type EN10MB (Ethernet)
Garbage Collection Began. Flows = 30
Exception in thread AsyncSniffer:
Traceback (most recent call last):
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/site-packages/scapy/sendrecv.py", line 1254, in _run
    session.on_packet_received(p)
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/site-packages/cicflowmeter/flow_session.py", line 107, in on_packet_received
    self.garbage_collect(packet.time)
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/site-packages/cicflowmeter/flow_session.py", line 125, in garbage_collect
    data = flow.get_data()
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/site-packages/cicflowmeter/flow.py", line 101, in get_data
    "timestamp": packet_time.get_time_stamp(),
  File "/home/eman/anaconda3/envs/py39/lib/python3.10/site-packages/cicflowmeter/features/packet_time.py", line 71, in get_time_stamp
    date_time = datetime.fromtimestamp(time).strftime("%Y-%m-%d %H:%M:%S")
TypeError: 'EDecimal' object cannot be interpreted as an integer

**Comment by hieulw** [comment]
what is your python version ?
