### ISSUE TITLE
Decimal error when convert pcap to csv

### ISSUE THREAD

**Issue by MuMuuuu** [hieulw/cicflowmeter#5]
Error : message

```
Garbage Collection Finished. Flows = 4
Garbage Collection Began. Flows = 4
Exception in thread AsyncSniffer:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 1275, in _run
    self.results = session.toPacketList()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/cicflowmeter-0.1.6-py3.11.egg/cicflowmeter/flow_session.py", line 35, in toPacketList
  File "/usr/local/lib/python3.11/dist-packages/cicflowmeter-0.1.6-py3.11.egg/cicflowmeter/flow_session.py", line 116, in garbage_collect
  File "/usr/local/lib/python3.11/dist-packages/cicflowmeter-0.1.6-py3.11.egg/cicflowmeter/flow.py", line 84, in get_data
  File "/usr/local/lib/python3.11/dist-packages/cicflowmeter-0.1.6-py3.11.egg/cicflowmeter/utils.py", line 29, in get_statistics
  File "/home/kali/.local/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 3504, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/numpy/core/_methods.py", line 131, in _mean
    ret = ret / rcount
          ~~~~^~~~~~~~
  File "/usr/lib/python3/dist-packages/scapy/utils.py", line 131, in __truediv__
    return EDecimal(Decimal.__truediv__(self, Decimal(other)))
                                              ^^^^^^^^^^^^^^
TypeError: conversion from numpy.int64 to Decimal is not supported
```

Environments

**Comment by hieulw** [comment]
how do you install this tool ? It looks like you're using the old version
